#!$(which zsh)
alias ls="exa -a --color=always --icons --group-directories-first"
alias ll="exa -la --color=always --icons --group-directories-first"
alias tree="exa -a --color=always --icons --group-directories-first -T"
alias lg="lazygit"
alias gt="gotop"
alias neo="neofetch"
alias aqua="asciiquarium"
alias nvide="neovide --frameless"
alias train="sl"
alias cl="clear" 
alias ~="cd"
alias ..="cd .."
alias nix-remove="nix-collect-garbage"
alias postgres-start="postgres -D /opt/homebrew/var/postgres"
alias mysql-start="mysqld_safe --datadir=/opt/homebrew/var/mysql"
